package com.soaint.informacioncliente;


import java.util.ArrayList;
import java.util.List;
import java.util.Iterator;


// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.3.0.0914


public class InformacionClienteClient {


    public static void main(String[] args) {


        ServicioInformacionCliente servicio = new ServicioInformacionCliente();
        InformacionClientePort port = servicio.getInformacionCliente();
        // Add your code to call the desired methods.

        ClienteType rq = new ClienteType();

        rq.setNumeroIdentificacion(44);

        ListaCLienteType rs = port.consultarClientes(rq);

        //// Now do it ..

        List<ClienteType> lista = new ArrayList<>();
        lista = rs.getListadoClientes();


        Iterator itera = lista.iterator();

        while (itera.hasNext()) {

            ClienteType empleado = (ClienteType) itera.next();

            System.out.println(empleado.getNombres());

        }

    }

}
